### ISSUE TITLE
json2csv.py can only be run under Python 3

### ISSUE THREAD

**Issue by avtaylor** [DocNow/twarc#257] opened 2018-11-02 14:48 UTC
Hello 
The understanding from readme was that twarc runs both under Python 2 and Python 3. 
But this file (json2csv.py) at least does not run under Python2.
Is there an equivalent file for python 2?

Thank you

**Comment by avtaylor** [comment] 2018-11-02 14:51
ok So i read a previous issue regarding the move towards python 3 mainly. So perhaps most examples then will run only for Python 3. Is this correct?
In that case perhaps it is reasonable to update the readme so that new users of twarc save time and install under Python 3

**Comment by edsu** [comment] 2018-11-02 15:19
Why do you think that json2csv.py does not run under Python2?

**Comment by avtaylor** [comment] 2018-11-02 15:35
Because when I run it on my machine where I had Python 2 installed I received an error saying that it can only run on Python 2:
"Sorry, json2csv.py requires python v3"

**Comment by edsu** [comment] 2018-11-02 15:52
Hmm, maybe that's an older version of the script? There is no message like that in the current source: https://github.com/DocNow/twarc/blob/master/utils/json2csv.py Can you try to update?

**Comment by hugovk** [comment] 2018-11-03 06:56
Python 2.7 support was added in August 2017:

https://github.com/DocNow/twarc/commit/9aa8af30fd667c7a867d5b0ebf2826d8ab536dc4

**Comment by edsu** [comment] 2018-11-03 14:31
I think the cause of this can be found in the comments for #258. Closing for now, but please reopen if the problem persists.

**Closed by edsu** 2018-11-03 14:31 UTC
