### ISSUE TITLE
UnicodeEncodeError using twarc utilities on Windows

### ISSUE THREAD

**Issue by eam5** [DocNow/twarc#297] opened 2019-09-17 19:58 UTC
I'm getting encoding errors when running some twarc utilities on windows. So far I'm getting similar error messages when running users.py, emojis.py, json2csv.py, tags.py, wall.py (this is what I've tested so far. wordcloud.py seems to work fine)

Python 3.7.4

![encode-error](https://user-images.githubusercontent.com/2805368/65074861-ac774c80-d963-11e9-8e54-4d7ce9c5fa7d.png)

I've tested the .jsonl file on my mac, and run all the above utilities successfully.

**Comment by eam5** [comment] 2019-11-04 15:49
An update to this - the solution I've found involves setting the system locale to UTF-8 (beta feature in Windows 10). See here: https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window/57134096#57134096

This works when using the Windows program Command Prompt to run the twarc utilities

**Comment by edsu** [comment] 2019-12-05 12:01
Many of the utilities and the twarc command itself use the fileinput module to open the input files. This is nice because it means the program can easily read from one or more files, as well as stdin, as a single source of input. With the `openhook=fileinput.hook_compressed` parameter you can also optionally allow the source file to be gzip compressed, which is handy when you want the utility to read from compressed data.

Unfortunately on Windows (currently) the default character encoding is `chcp-65001` instead of `utf-8`.  This means twarc utilities (and twarc itself) will not be able to decode JSON properly. You can use an openhook to force the encoding. But you can't use multiple openhooks.

I think the solution here is to create our own openhook that looks to see if the file is gzip encoded, and also forces utf8. This should be pretty easy on python3, but the gzip + utf8 decoding is a bit tricky on python2.

So I think resolving this issue is a [good reason](https://pythonclock.org/) to finally switch to Python3 only support and let Python2 go.

**Comment by melaniewalsh** [comment] 2020-03-10 17:25
I'm teaching twarc in my class this week, and I just wanted to note that students with Windows computers are also getting utf8-related errors when using twarc utilities, specifically json2csv.py. I'm going to suggest that they set the system locale to utf-8, but I just wanted to ping the issue here.

**Comment by juanulload** [comment] 2020-09-03 22:04
I'm having a similar issue with my utilities. Tried the 'system locale to utf-8' solution but nothing, keep getting this:
![error_twarc_util](https://user-images.githubusercontent.com/17188625/92177885-5bc86000-ee0f-11ea-8789-022a8474f592.png)

I'm not sure how to implement the solution mentioned by @edsu (I have python3 in my PC)

**Comment by edsu** [comment] 2020-11-23 19:02
While doing some experiments with Alejandra Josiowicz that twarc writes JSON data using UTF-16 on Windows. The twarc utilities mostly assume utf-16 output. I think one way of solving this would be to ensure that twarc outputs utf-8?

**Comment by igorbrigadir** [comment] 2021-03-21 23:57
I just realized this is the same error: https://github.com/DocNow/twarc/wiki/twarc2-on-Windows-10#output-format-errors for anyone else looking, the issue is with `>` redirecting output like that will write in UTF-16 on windows and put a Byte Order Mark into the file.

**Comment by edsu** [comment] 2021-03-22 09:51
Thanks for making this connection @igorbrigadir !I really like being able to use twarc in pipelines so it is a bummer to have to update the docs to not use >. But I guess we could have a prominent section in the documentation about twarc on windows that explains this, and make sure the command have a way to write to a file?

**Comment by igorbrigadir** [comment] 2021-03-22 12:18
oh! I had another look, and I think this is the solution: https://jpsoft.com/blogs/2020/04/redirection-piping-and-unicode-at-the-windows-command-prompt/

so this should work:

`twarc ... >:u8 output.json`

(i haven't checked this on Windows yet)

**Comment by edsu** [comment] 2021-03-22 16:29
I was just looking at that. I'd love to know if that works!

**Comment by igorbrigadir** [comment] 2021-09-28 10:32
Going through closing some old issues: the best solution for Windows is to never use the `>` output redirection and instead specify a file name output, like `twarc2 search "..." output.jsonl`

**Closed by igorbrigadir** 2021-09-28 10:32 UTC
