### ISSUE TITLE
HTTPError 422

### ISSUE THREAD

**Issue by santoshbs** [DocNow/twarc#360] opened 2020-10-28 20:28 UTC
When I run this command-line, I get an error:

`twarc --app_auth search 'blacklivesmatter from:intel' --fullarchive dev --sandbox
`

`requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.twitter.com/1.1/tweets/search/fullarchive/dev.json?query=blacklivesmatter+from%3Aintel&maxResults=100&tweet_mode=extended`

Not sure how to resolve this issue.

**Comment by edsu** [comment] 2020-10-28 20:39
It looks like that 422 error is [listed](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/search/api-reference/premium-search) as: 

> This is returned due to invalid parameters in the query -- e.g. invalid PowerTrack rules.

It seems from the [description](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/search/guides/fas-timeline) of the full-archive api that your query should work. 

Does it help to modify your query at all? I don't have access to the full-archive myself.

**Comment by Enchufa2** [comment] 2020-12-14 11:09
I'm experiencing the same issue with the 30day endpoint. The documentation says that [a bearer token is required](https://developer.twitter.com/en/docs/twitter-api/premium/search-api/quick-start/premium-30-day). Could this be the issue? Has twarc support for this kind of authentication?

**Comment by edsu** [comment] 2020-12-14 12:18
It does have support. What query are you trying to use? Does adjusting/simplifying it help at all?

**Comment by Enchufa2** [comment] 2020-12-14 12:33
Similar query to the one reported above, but with `--30day dev --sandbox` instead. Simplifying the query to a single term, no dates, no nothing doesn't help.

**Comment by edsu** [comment] 2020-12-14 13:17
I can confirm I'm seeing the same behavior and I think that the `maxResults` and `tweet_mode` parameters that are being passed now cause problems. I think I can get a fix for this in the next few hours.

**Comment by Enchufa2** [comment] 2020-12-14 13:34
Thanks. FWIW, the documentation contains examples with `maxResults`, but not with `tweet_mode`. And it's strange that all parameters are camel case except for `tweet_mode`.

**Comment by edsu** [comment] 2020-12-14 13:41
Yeah, it is weird. They are from the Twitter API itself, and not twarc.

**Comment by edsu** [comment] 2020-12-14 14:30
The problem was that the premium endpoints no longer like being given the  `tweet_mode` parameter.  Can you give v1.12.1 (just released) a try?

**Closed** 2020-12-14 14:30 UTC

**Comment by Enchufa2** [comment] 2020-12-14 14:37
The new version works great, thanks for the quick patch!

**Comment by edsu** [comment] 2020-12-14 15:08
Thanks for testing, and not giving up!
