### ISSUE TITLE
wall.py not working with extended tweets

### ISSUE THREAD

**Issue by alblaine** [DocNow/twarc#201] opened 2018-01-02 19:11 UTC
Getting an error message when using wall.py -- seems to be an extended tweet issue: 
 File "utils/wall.py", line 145, in <module>
    "text": tweet["text"],
KeyError: 'text'

**Comment by edsu** [comment] 2018-01-02 21:20
This is a duplicate of #180

**Closed by edsu** 2018-01-02 21:20 UTC

**Comment by edsu** [comment] 2018-01-02 21:22
I'm sorry if my closing of the ticket seemed brusque. I will update this ticket once #180 is resolved to let you know that you can update your wall.py.

**Comment by alblaine** [comment] 2018-01-02 21:31
Sorry, didn't see that. Thanks. Looks like the CSS on wall.py will need to be modified to accomodate longer tweets as well.

**Comment by edsu** [comment] 2018-01-02 21:58
Ok, I've updated wall.py to hopefully extract text from new-style and old-style tweet JSON data. I've also adjusted the CSS but ideas are definitely welcome for improving the layout/presentation.
